### PR TITLE
add correct expiry time definition and set to 60m

### LINKED ISSUE #53: Token expiry is in milliseconds, not seconds
https://github.com/fusion44/blitz_api/blob/main/.env_sample#L3 says expiry time in seconds.

Running a few tests, I conclude these are in fact milliseconds :)

### PR DESCRIPTION
**Pull request by cstenglein**
fixes #53 

Please merge soon because it's blocking https://github.com/cstenglein/raspiblitz-web/issues/146 (otherwise the token gets refreshed all the time)

### CODE REVIEW

**Comment by rootzoll** [comment]
@cstenglein that default value does not seem to work

```
Jun 06 13:16:41 python[36779]: ValueError: invalid literal for int() with base 10: '3_600_000 # 1 hour'
```

**Comment by rootzoll** [comment]
correcting to 3600000

**Comment by cstenglein** [comment]
What Python version is used?

Should Work since Python 3.6: https://peps.python.org/pep-0515/

**Comment by rootzoll** [comment]
its `Python 3.9.2` .. maybe ist also because of the comment at the end. But seems to be good now with my fix.

**Pull request merged**
