### PR TITLE
Abstract platform implementations away

### PR DESCRIPTION
**Pull request by fusion44**
Currently RaspiBlitz platform "bleeds" into native python platform a lot which leads to undesired behaviour and spaghetti code. Abstract away the code for each platform so the don't intermingle.

See https://github.com/fusion44/blitz_api/issues/143
ToDo:
* [x] Apps
* [x] System
* [x] Hardware
* [x] Setup

### CODE REVIEW

**Comment by fusion44** [comment]
@rootzoll @cstenglein This should be pretty much ready, please test. I can't really test the setup part right now though.

**Comment by ChuckNorrison** [comment]
> @rootzoll @cstenglein This should be pretty much ready, please test. From my tests everything should work as expected. I can't really test the setup part right now though.

i tried to test the branch on my pi by removing the api and install manually with the requirements.txt fix. After login into the webinterface it ends on a white page.

i think the web and api branches are not compatible

maybe this can help to get the webui fixed

**Comment by cstenglein** [comment]
Thanks for testing @ChuckNorrison !

when using this branch from the webui, the screen should appear again. will need to test refresh token & setup though.

https://github.com/cstenglein/raspiblitz-web/pull/505

**Comment by cstenglein** [comment]
Tried to install this branch with the 1.8.0c image:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.9/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.9'
Call stack:
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.9/logging/__init__.py", line 1442, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.1.2', new='22.3.1'),)
error='pip install failed'

**Comment by fusion44** [comment]
> Tried to install this branch with the 1.8.0c image:
> 
> ```
> --- Logging error ---
> ...
> ```

This should be fixed with this issue: https://github.com/fusion44/blitz_api/issues/161#issuecomment-1324037652

**Comment by cstenglein** [comment]
Updated to this branch with the latest dev image & restarted.

API failed with the following error:

```
Nov 28 06:37:22 raspberrypi systemd[1]: Started BlitzBackendAPI.
Nov 28 06:37:25 raspberrypi python[39690]: Traceback (most recent call last):
Nov 28 06:37:25 raspberrypi python[39690]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Nov 28 06:37:25 raspberrypi python[39690]:     return _run_code(code, main_globals, None,
Nov 28 06:37:25 raspberrypi python[39690]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
Nov 28 06:37:25 raspberrypi python[39690]:     exec(code, run_globals)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/__main__.py", line 4, in <module>
Nov 28 06:37:25 raspberrypi python[39690]:     uvicorn.main()
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Nov 28 06:37:25 raspberrypi python[39690]:     return self.main(*args, **kwargs)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
Nov 28 06:37:25 raspberrypi python[39690]:     rv = self.invoke(ctx)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Nov 28 06:37:25 raspberrypi python[39690]:     return ctx.invoke(self.callback, **ctx.params)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
Nov 28 06:37:25 raspberrypi python[39690]:     return __callback(*args, **kwargs)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 408, in main
Nov 28 06:37:25 raspberrypi python[39690]:     run(
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
Nov 28 06:37:25 raspberrypi python[39690]:     server.run()
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
Nov 28 06:37:25 raspberrypi python[39690]:     return asyncio.run(self.serve(sockets=sockets))
Nov 28 06:37:25 raspberrypi python[39690]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Nov 28 06:37:25 raspberrypi python[39690]:     return loop.run_until_complete(main)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Nov 28 06:37:25 raspberrypi python[39690]:     return future.result()
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
Nov 28 06:37:25 raspberrypi python[39690]:     config.load()
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
Nov 28 06:37:25 raspberrypi python[39690]:     self.loaded_app = import_from_string(self.app)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
Nov 28 06:37:25 raspberrypi python[39690]:     module = importlib.import_module(module_str)
Nov 28 06:37:25 raspberrypi python[39690]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Nov 28 06:37:25 raspberrypi python[39690]:     return _bootstrap._gcd_import(name[level:], package, level)
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Nov 28 06:37:25 raspberrypi python[39690]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Nov 28 06:37:25 raspberrypi python[39690]:   File "./app/main.py", line 20, in <module>
Nov 28 06:37:25 raspberrypi python[39690]:     from app.api.warmup import (
Nov 28 06:37:25 raspberrypi python[39690]:   File "./app/api/warmup.py", line 6, in <module>
Nov 28 06:37:25 raspberrypi python[39690]:     from app.lightning.service import (
Nov 28 06:37:25 raspberrypi python[39690]:   File "./app/lightning/service.py", line 59, in <module>
Nov 28 06:37:25 raspberrypi python[39690]:     ln = LnNode()
Nov 28 06:37:25 raspberrypi python[39690]: NameError: name 'LnNode' is not defined
```

**Comment by fusion44** [comment]
Closing this PR as the branch will be renamed to dev and will live on.

**Pull request closed without merging**
